healthcheck:
  path: /api/healthcheck
  controller: Department\Infrastructure\Controller\HealthCheckAction
  methods: GET

login:
  path: /api/auth/login
  controller: Department\Infrastructure\Controller\LoginAction
  methods: POST|OPTIONS

#refresh:
#  path: /api/auth/refresh
#  controller: Department\Infrastructure\Controller\RefreshAction
#  methods: POST
