parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Department\:
        resource: '../src/'
        exclude:
#            - '../src/DependencyInjection/'
#            - '../src/Entity/'
#            - '../src/Kernel.php'
#            - '../src/Tests/'

    Department\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

imports:
    - { resource: '../src/Module/Auth/services.yaml' }
