departmentCreate:
  path: /api/department/create
  controller: Department\Infrastructure\Controller\DepartmentCreateAction
  methods: POST

#departmentUpdate:
#  path: /api/department/update
#  controller: Department\Infrastructure\Controller\DepartmentUpdateAction
#  methods: POST

departmentDelete:
  path: /api/department/delete
  controller: Department\Infrastructure\Controller\DepartmentDeleteAction
  methods: POST