departmentCreate:
  path: /api/department/create
  controller: Department\Infrastructure\Controller\Department\DepartmentCreateAction
  methods: POST

departmentUpdate:
  path: /api/department/update
  controller: Department\Infrastructure\Controller\Department\DepartmentUpdateAction
  methods: POST

departmentDelete:
  path: /api/department/delete
  controller: Department\Infrastructure\Controller\Department\DepartmentDeleteAction
  methods: POST

departmentList:
  path: /api/department/public/list
  controller: Department\Infrastructure\Controller\Department\DepartmentListAction
  methods: GET
  
departmentView:
  path: /api/department/public/view
  controller: Department\Infrastructure\Controller\Department\DepartmentViewAction
  methods: POST

departmentViewAuth:
  path: /api/department/view
  controller: Department\Infrastructure\Controller\Department\DepartmentViewAction
  methods: POST

departmentViewGrade:
  path: /api/department/public/view/grade
  controller: Department\Infrastructure\Controller\Department\DepartmentViewGradeAction
  methods: POST
