employeeCreate:
  path: /api/employee/create
  controller: Department\Infrastructure\Controller\Employee\EmployeeCreateAction
  methods: POST

employeeUpdate:
  path: /api/employee/update
  controller: Department\Infrastructure\Controller\Employee\EmployeeUpdateAction
  methods: POST

employeeDelete:
  path: /api/employee/delete
  controller: Department\Infrastructure\Controller\Employee\EmployeeDeleteAction
  methods: POST