gradeCreate:
  path: /api/grade/create
  controller: Department\Infrastructure\Controller\Grade\GradeCreateAction
  methods: POST

gradeUpdate:
  path: /api/grade/update
  controller: Department\Infrastructure\Controller\Grade\GradeUpdateAction
  methods: POST

gradeDelete:
  path: /api/grade/delete
  controller: Department\Infrastructure\Controller\Grade\GradeDeleteAction
  methods: POST