doctrine:
    dbal:
        url: '%env(resolve:DB_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            enum_grade_type: Department\Infrastructure\Doctrine\Type\GradeType
            enum_department_type: Department\Infrastructure\Doctrine\Type\DepartmentType
            phone_type: Department\Infrastructure\Doctrine\Type\PhoneType
            email_type: Department\Infrastructure\Doctrine\Type\EmailType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Employee:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Employee'
                prefix: 'Department\Module\Employee\Model'
                alias: Employee
            Department:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Department'
                prefix: 'Department\Module\Department\Model'
                alias: Department
            Grade:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Grade'
                prefix: 'Department\Module\Grade\Model'
                alias: Grade
            Auth:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Auth'
                prefix: 'Department\Module\Auth\Model'
                alias: Auth