gesdinet_jwt_refresh_token:
#    refresh_token_class: Department\Module\Auth\Model\RefreshToken
#    token_parameter_name: refreshToken
#    return_expiration: true
#    return_expiration_parameter_name: refresh_token_expiration
